# Generated by Django 4.0.6 on 2022-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('writer', models.CharField(max_length=50, verbose_name='Автор')),
                ('img', models.ImageField(upload_to='', verbose_name='img')),
                ('status', models.BooleanField(verbose_name='Статус')),
                ('date', models.DateField(verbose_name='')),
            ],
        ),
    ]
