# Generated by Django 4.0.6 on 2022-07-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='booked',
            field=models.BooleanField(default=False, verbose_name='Бронь'),
        ),
        migrations.AddField(
            model_name='book',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Время'),
        ),
    ]
