# Generated by Django 4.0.6 on 2022-07-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_book_date_remove_book_status_book_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
